# from https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
# from https://github.com/academicpages/academicpages.github.io/blob/master/_config.yml

remote_theme: jekyll/minima
locale                   : "en-US"
title: Passing Thoughts
name: U9G Name
author: U9G
url                      : https://blog.u9g.dev # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"

social-network-links:
  email: "blog@u9g.dev"
  rss: true
  github: u9g

post_search: true

utterances:
  repo: u9g/u9g.github.io # GitHub username/repository eg. "daattali/beautiful-jekyll"
  theme: github-dark # Utterances theme
  issue-term: "pathname"
  #label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

navbar-links:
  Home: "https://blog.u9g.dev"
